#!/usr/bin/env python
#
# Copyright 2007 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import webapp2


class MainHandler(webapp2.RequestHandler):
    def get(self):
            add_form = """
            <form action="/submit" method="post">
                <label>
                    Username
                    <input type="text" name="Username"/>
                </label>
                <br>
                <label>
                    Password
                    <input type="password" name="Password"/>
                </label>
                <br>
                <label>
                    Verify Password
                    <input type="password" name="Verify"/>
                </label>
                <br>
                <label>
                    Email(optional)
                    <input type="text" name="Email"/>
                </label>
                <br>
                <input type="submit" value="Submit"/>
            </form>
            """
            content = add_form
            self.response.write(content)


class Welcome(webapp2.RequestHandler):


    def post(self):

        User = self.request.get("Username")
        content = "welcome " + User
        self.response.write(content)
         def get(self):
        self.render("index.html")

    def post(self):
        # Error messages
        username_error = invalid_email = invalid_password = verify_password_error = None

        user_username = self.request.get("username")
        user_password = self.request.get("password")
        user_verify_password = self.request.get("verify")
        user_email = self.request.get("email")

        username = valid_name(user_username)
        password = valid_password(user_password)
        verify_password = None
        email = None

        if user_email:
            email = valid_email(user_email)
            if not email:
                invalid_email = "That's not a valid email."

        if not username:
            username_error = "That's not a valid username."

        if password:
            verify_password = valid_verify_password(user_password, user_verify_password)
            if not verify_password:
                verify_password_error = "Your passwords didn't match."
        else:
            invalid_password = "That wasn't a valid password."

        if username and password and verify_password and not invalid_email:
            self.redirect("/welcome?username=%s"%(user_username))
        else:
            self.render("index.html",
            username_error = username_error,
            username = user_username,
            invalid_password = invalid_password,
            verify_password_error = verify_password_error,
            invalid_email = invalid_email,
            email = user_email)

class WelcomePage(Handler):
    def get(self):
        username = self.request.get("username")
        self.write("Thanks for signing up %s" % (username))
        
        
class MainHandler(webapp2.RequestHandler):
    def get(self):
        self.response.write('Sign Up!')

app = webapp2.WSGIApplication([
    ('/', MainHandler)
], debug=True)

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
 
